[package]
name = "task_processor"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.7"
serde = { version = "1.0.215", features = ["derive"] }
notify = "7.0.0"
tokio = { version = "1.41.1", features = ["fs", "rt-multi-thread", "rt", "macros"] }
serde_json = "1.0.132"
dotenvy = "0.15.7"